### ISSUE TITLE
Error in simple_triplet_matrix

### ISSUE THREAD

**Issue by cpsievert** [OhLookCake/xkcd-Topics#1]
I get the following error originating [here](https://github.com/CabbagesAndKings/xkcd-Topics/blob/master/scripts/topicExtraction.R#L56-57):

```
> dtm <- DocumentTermMatrix(Corpus(VectorSource(dfTranscripts$text)),
+                         control = dtm.control)
Error in simple_triplet_matrix(i = i, j = j, v = as.numeric(v), nrow = length(allTerms),  : 
  'i, j, v' different lengths
In addition: Warning messages:
1: In parallel::mclapply(x, termFreq, control) :
  all scheduled cores encountered errors in user code
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In simple_triplet_matrix(i = i, j = j, v = as.numeric(v), nrow = length(allTerms),  :
  NAs introduced by coercion
```

Here is my sessionInfo:

```
> sessionInfo()
R version 3.0.1 (2013-05-16)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] topicmodels_0.1-12 tm_0.5-9.1        

loaded via a namespace (and not attached):
[1] modeltools_0.2-21 parallel_3.0.1    slam_0.1-30       stats4_3.0.1      tools_3.0.1 
```

**Comment by OhLookCake** [comment]
A colleague had the same issue. Apparently it arises because of some compatibility issue between an older version of snowballC and a later version of tm. 

`install.packages("SnowballC")`

should do the trick.

**Comment by cpsievert** [comment]
That did the trick indeed. Thanks!

**Comment by bklugah** [comment]
I still have same problem even after installing the snowballC.
what could possibly be the problem
install.packages("SnowballC")
plot(dtm,terms=findFreqTerms(dtm,lowfreq = 40)[1:50],corThreshold=0.5)
**Error in `[.simple_triplet_matrix`(m, , terms) : NA indices not allowed**.

**Comment by OhLookCake** [comment]
I don't see that line in any script in the repo. Can you point  me to it? Also, I don't see why this behaviour is unexpected at all - somewhere the findFreqTerms function is trying to access NA indices. (Again, I have no idea where, because this doesn't seem to be a snippet from my code.

**Comment by psurendar** [comment]
I've got the following error while trying to create a sparseTermMatrix.  Then I tried to comment the plain text code and run. It works.  
Error in simple_triplet_matrix(i, j, v, nrow = length(terms), ncol = length(corpus),  : 'i, j' invalid
#corpusRemoved = tm_map(corpusRemoved, PlainTextDocument)
dtmRemoved= DocumentTermMatrix(corpusRemoved)

What happened ?: If you try to convert all text corpus into PlainTextDocument, the DocumentTermMatrix fails to work on the plain text document.

**Comment by parwani-b** [comment]
I am still getting this error. I will really appreciate if someone could help me on this. I am also attaching my R code snippet. Please help.
![jeopardy worcloud code](https://user-images.githubusercontent.com/25044666/34783024-625c1dce-f5f8-11e7-9f1f-3020f6f7059d.PNG)

![r error](https://user-images.githubusercontent.com/25044666/34782927-25c701da-f5f8-11e7-86af-abf1277391f5.PNG)

**Comment by kumarh22** [comment]
Just try **VCorpus** instead of Corpus as below...
_jeopCorpus <- VCorpus(VectorSource(jeopQ$Question))_

and proceed, hope it will work....

**Comment by jdstallings** [comment]
VCorpus worked for me 👍 Thanks Halake

**Comment by renaudmontes1** [comment]
Wow, VCorpus worked for me too! You saved my week! Thank you, thank you!

**Comment by mr-sachinpardeshi** [comment]
> Just try **VCorpus** instead of Corpus as below...
> _jeopCorpus <- VCorpus(VectorSource(jeopQ$Question))_
> 
> and proceed, hope it will work....

Thanks VCorpus worked for me too! Thank you once again

**Comment by ZabihBuda** [comment]
> Just try **VCorpus** instead of Corpus as below...
> _jeopCorpus <- VCorpus(VectorSource(jeopQ$Question))_
> 
> and proceed, hope it will work....



> VCorpus worked for me 👍 Thanks Halake

The VCorpus worked for me too. Thank you.

**Comment by renaudmontes1** [comment]
Thanks will try like that!
Renaud

On Jun 26, 2020, at 7:04 PM, Zabihullah Zabih <notifications@github.com<mailto:notifications@github.com>> wrote:


Just try VCorpus instead of Corpus as below...
jeopCorpus <- VCorpus(VectorSource(jeopQ$Question))

and proceed, hope it will work....

VCorpus worked for me 👍 Thanks Halake

The VCorpus worked for me too. Thank you.
